name: los-lirios-sa
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/los-lirios-sa  # Cambiar por tu repo
  name: web
  source_dir: /
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs  # $5/mes
  routes:
  - path: /
  run_command: |
    python manage.py collectstatic --noinput
    python manage.py migrate --noinput
    gunicorn --worker-tmp-dir /dev/shm los_lirios_sa.wsgi
  envs:
  - key: DJANGO_ENV
    value: production
    type: SECRET
  - key: DJANGO_SECRET_KEY
    value: your-secret-key-here
    type: SECRET
  - key: DEBUG
    value: "False"
    type: SECRET
databases:
- engine: PG
  name: loslirios-db
  num_nodes: 1
  size: db-s-dev-database  # $15/mes
  version: "14"