# Generated by Django 5.2.1 on 2025-06-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='finca',
            field=models.CharField(choices=[('Los Mimbres', 'Los Mimbres'), ('Media Agua', 'Media Agua'), ('Caucete', 'Caucete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='tipo',
            field=models.CharField(choices=[('Sueldos Personal', 'Sueldos Personal'), ('Produccion', 'Producción'), ('Inversion', 'Inversión'), ('Insumos Varios', 'Insumos Varios'), ('Impuestos o Servicios', 'Impuestos o Servicios')], max_length=30),
        ),
    ]
