# Generated by Django 5.2.1 on 2025-07-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0003_alter_movimientofinanciero_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre único de la parcela, ej: 'Parral 16'", max_length=100, unique=True)),
                ('variedad', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('cabezal_riego', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cabezal de Riego')),
                ('coordenadas', models.JSONField(help_text='Lista de coordenadas [[lat, lon], ...] que forman el polígono.', null=True)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['nombre'],
            },
        ),
    ]
