# Generated by Django 5.2.1 on 2025-09-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0005_registroriego'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroriego',
            old_name='valvulas_abiertas',
            new_name='valvula_abierta',
        ),
    ]
