# Generated by Django 5.2.1 on 2025-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0008_ingresofinanciero'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('origen', models.CharField(choices=[('Terceros', 'Terceros'), ('Los Lirios', 'Los Lirios')], max_length=20)),
                ('finca', models.CharField(max_length=50)),
                ('destino', models.CharField(choices=[('Bodega', 'Bodega'), ('Descarte', 'Descarte'), ('Exportacion', 'Exportación'), ('Fardo', 'Fardo'), ('Mercado Interno', 'Mercado Interno'), ('Pasa', 'Pasa'), ('Rama Pasa', 'Rama Pasa'), ('Semilla', 'Semilla')], max_length=50)),
                ('comprador', models.CharField(max_length=100)),
                ('cultivo', models.CharField(max_length=50)),
                ('parral_potrero', models.CharField(max_length=100, verbose_name='Parral/Potrero')),
                ('variedad', models.CharField(max_length=50)),
                ('remito', models.CharField(max_length=50, verbose_name='Número de Remito')),
                ('ciu', models.IntegerField(blank=True, null=True, verbose_name='CIU (Solo para uva de bodega)')),
                ('medida', models.CharField(choices=[('Caja', 'Caja'), ('Bin', 'Bin'), ('Chasis', 'Chasis')], max_length=20)),
                ('peso_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Unitario (Kg)')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad de cajas/bins')),
                ('bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Bruto (Kg)')),
                ('tara', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tara (Kg)')),
                ('kg_totales', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Totales')),
            ],
            options={
                'verbose_name': 'Registro de Cosecha',
                'verbose_name_plural': 'Registros de Cosecha',
                'ordering': ['-fecha'],
            },
        ),
    ]
