# Generated by Django 5.2.1 on 2025-11-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0009_registrocosecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompradorIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comprador de Ingreso',
                'verbose_name_plural': 'Compradores de Ingresos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DestinoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destino de Ingreso',
                'verbose_name_plural': 'Destinos de Ingresos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='ingresofinanciero',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='ingresofinanciero',
            name='finca',
        ),
        migrations.AddField(
            model_name='ingresofinanciero',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingresofinanciero',
            name='comprador',
            field=models.CharField(default=1, max_length=100, verbose_name='Comprador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresofinanciero',
            name='destino',
            field=models.CharField(default='nadie', max_length=100, verbose_name='Destino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresofinanciero',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='ingresofinanciero',
            name='forma',
            field=models.CharField(choices=[('Caja', 'Caja'), ('Bsj', 'Bsj'), ('MP camilo', 'MP camilo'), ('GM', 'GM'), ('Naranja Nico', 'Naranja Nico'), ('Galicia Nico', 'Galicia Nico')], default='Caja', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresofinanciero',
            name='numero_cheque',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Cheque'),
        ),
        migrations.AlterField(
            model_name='ingresofinanciero',
            name='forma_pago',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Echeque', 'Echeque')], max_length=20),
        ),
    ]
