# Generated by Django 5.2.1 on 2025-11-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0010_compradoringreso_destinoingreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_analisis_data', 'Can view analysis dashboards')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProduccionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_produccion_data', 'Can view production data')],
                'managed': False,
            },
        ),
    ]
