# Generated by Django 4.2.26 on 2025-11-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0011_analisispermission_produccionpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompradorCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comprador de Cosecha',
                'verbose_name_plural': 'Compradores de Cosecha',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CultivoCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cultivo de Cosecha',
                'verbose_name_plural': 'Cultivos de Cosecha',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FincaCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Finca de Cosecha',
                'verbose_name_plural': 'Fincas de Cosecha',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VariedadCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Variedad de Cosecha',
                'verbose_name_plural': 'Variedades de Cosecha',
                'ordering': ['nombre'],
            },
        ),
    ]
