# Generated by Django 4.2.26 on 2025-11-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0012_compradorcosecha_cultivocosecha_fincacosecha_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ingresofinanciero',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_dec4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresofinanciero',
            index=models.Index(fields=['forma_pago'], name='contabilida_forma_p_77cd16_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresofinanciero',
            index=models.Index(fields=['fecha_pago'], name='contabilida_fecha_p_f373ed_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresofinanciero',
            index=models.Index(fields=['comprador'], name='contabilida_comprad_21101a_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresofinanciero',
            index=models.Index(fields=['destino'], name='contabilida_destino_3e203c_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresofinanciero',
            index=models.Index(fields=['origen'], name='contabilida_origen_403b88_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresofinanciero',
            index=models.Index(fields=['forma_pago', 'fecha_pago'], name='contabilida_forma_p_95e5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresofinanciero',
            index=models.Index(fields=['fecha', 'forma_pago'], name='contabilida_fecha_f46c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresofinanciero',
            index=models.Index(fields=['monto'], name='contabilida_monto_9e3ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_2351f8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['tipo'], name='contabilida_tipo_c0614d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['clasificacion'], name='contabilida_clasifi_af68c5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['origen'], name='contabilida_origen_154cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['finca'], name='contabilida_finca_b33292_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['forma_pago'], name='contabilida_forma_p_621f24_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['fecha', 'tipo'], name='contabilida_fecha_a2a16c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['fecha', 'origen'], name='contabilida_fecha_3205da_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['moneda', 'fecha'], name='contabilida_moneda_f99bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['monto'], name='contabilida_monto_2bfb37_idx'),
        ),
        migrations.AddIndex(
            model_name='registro_trabajo',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_4edd46_idx'),
        ),
        migrations.AddIndex(
            model_name='registro_trabajo',
            index=models.Index(fields=['nombre_trabajador'], name='contabilida_nombre__12818e_idx'),
        ),
        migrations.AddIndex(
            model_name='registro_trabajo',
            index=models.Index(fields=['clasificacion'], name='contabilida_clasifi_6a5e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='registro_trabajo',
            index=models.Index(fields=['ubicacion'], name='contabilida_ubicaci_287e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='registro_trabajo',
            index=models.Index(fields=['fecha', 'clasificacion'], name='contabilida_fecha_4ffc34_idx'),
        ),
        migrations.AddIndex(
            model_name='registro_trabajo',
            index=models.Index(fields=['fecha', 'nombre_trabajador'], name='contabilida_fecha_322565_idx'),
        ),
        migrations.AddIndex(
            model_name='registro_trabajo',
            index=models.Index(fields=['tarea'], name='contabilida_tarea_1e28d1_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_5cbd17_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['finca'], name='contabilida_finca_9ba85a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['variedad'], name='contabilida_varieda_a06e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['destino'], name='contabilida_destino_a376f5_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['comprador'], name='contabilida_comprad_034cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['origen'], name='contabilida_origen_358e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['fecha', 'finca'], name='contabilida_fecha_1961b4_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['fecha', 'variedad'], name='contabilida_fecha_727304_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocosecha',
            index=models.Index(fields=['kg_totales'], name='contabilida_kg_tota_240093_idx'),
        ),
        migrations.AddIndex(
            model_name='registroriego',
            index=models.Index(fields=['inicio'], name='contabilida_inicio_222482_idx'),
        ),
        migrations.AddIndex(
            model_name='registroriego',
            index=models.Index(fields=['cabezal'], name='contabilida_cabezal_1c7e63_idx'),
        ),
        migrations.AddIndex(
            model_name='registroriego',
            index=models.Index(fields=['parral'], name='contabilida_parral_16529e_idx'),
        ),
        migrations.AddIndex(
            model_name='registroriego',
            index=models.Index(fields=['responsable'], name='contabilida_respons_b5e170_idx'),
        ),
        migrations.AddIndex(
            model_name='registroriego',
            index=models.Index(fields=['inicio', 'cabezal'], name='contabilida_inicio_643b84_idx'),
        ),
    ]
