# Generated by Django 5.2.1 on 2025-06-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('origen', models.CharField(choices=[('Oficial', 'Oficial'), ('No Oficial', 'No Oficial')], max_length=20)),
                ('finca', models.CharField(choices=[('Los Mimbres', 'Los Mimbres'), ('Media Agua', 'Media Agua')], max_length=20)),
                ('tipo', models.CharField(choices=[('Sueldos Personal', 'Sueldos Personal'), ('Produccion', 'Producción'), ('Inversion', 'Inversión'), ('Insumos Varios', 'Insumos Varios'), ('Impuestos/Servicios', 'Impuestos/Servicios')], max_length=30)),
                ('clasificacion', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'USD')], max_length=3)),
                ('forma_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Credito', 'Crédito'), ('Cheque', 'Cheque')], max_length=20)),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha'],
                'permissions': [('can_view_movimientos', 'Can view all financial movements'), ('can_add_movimientos', 'Can add new financial movements'), ('can_export_movimientos', 'Can export financial movements data')],
            },
        ),
        migrations.CreateModel(
            name='registro_trabajo',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre_trabajador', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(choices=[('General', 'General'), ('Verano', 'Verano'), ('Otoño', 'Otoño'), ('Invierno', 'Invierno'), ('Primavera', 'Primavera')], default='General', max_length=20)),
                ('detalle', models.CharField(default='N/A', max_length=255)),
                ('tarea', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Registro de Trabajo',
                'verbose_name_plural': 'Registros de Trabajo',
                'permissions': [('can_view_jornales', 'Can view all jornal entries'), ('can_add_jornales', 'Can add new jornal entries'), ('can_export_jornales', 'Can export jornal data')],
            },
        ),
    ]
