# Generated by Django 5.2.1 on 2025-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0002_alter_movimientofinanciero_finca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='tipo',
            field=models.CharField(choices=[('Sueldos Personal', 'Sueldos Personal'), ('Produccion', 'Producción'), ('Inversion', 'Inversión'), ('Repuestos y Reparaciones', 'Repuestos y Reparaciones'), ('Insumos Varios', 'Insumos Varios'), ('Impuestos o Servicios', 'Impuestos o Servicios'), ('Energia', 'Energía')], max_length=30),
        ),
    ]
