# Generated by Django 5.2.1 on 2025-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0004_parcela'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRiego',
            fields=[
                ('id_riego', models.AutoField(primary_key=True, serialize=False)),
                ('cabezal', models.CharField(max_length=50, verbose_name='Cabezal')),
                ('parral', models.CharField(max_length=100, verbose_name='Parral/Potrero')),
                ('valvulas_abiertas', models.CharField(help_text="Valvulas seleccionadas, ej: '1,3'", max_length=50)),
                ('inicio', models.DateTimeField(verbose_name='Inicio de Operación')),
                ('fin', models.DateTimeField(verbose_name='Fin de Operación')),
                ('fertilizante_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Fertilizante')),
                ('fertilizante_litros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Litros de Fertilizante')),
                ('responsable', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Registro de Riego',
                'verbose_name_plural': 'Registros de Riego',
                'ordering': ['-inicio'],
                'permissions': [('can_view_riego', 'Can view irrigation data'), ('can_add_riego', 'Can add new irrigation entries')],
            },
        ),
    ]
