# Generated by Django 5.2.1 on 2025-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0006_rename_valvulas_abiertas_registroriego_valvula_abierta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_trabajo',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
