# Generated by Django 5.2.1 on 2025-09-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_loslirios', '0007_registro_trabajo_monto_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoFinanciero',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('origen', models.CharField(choices=[('Oficial', 'Oficial'), ('No Oficial', 'No Oficial')], max_length=20)),
                ('finca', models.CharField(choices=[('Los Mimbres', 'Los Mimbres'), ('Media Agua', 'Media Agua'), ('Caucete', 'Caucete')], max_length=20)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'USD')], max_length=3)),
                ('forma_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Credito', 'Crédito'), ('Cheque', 'Cheque')], max_length=20)),
            ],
            options={
                'verbose_name': 'Ingreso Financiero',
                'verbose_name_plural': 'Ingresos Financieros',
                'ordering': ['-fecha'],
                'permissions': [('can_view_ingresos', 'Can view all financial incomes'), ('can_add_ingresos', 'Can add new financial incomes'), ('can_export_ingresos', 'Can export financial incomes data')],
            },
        ),
    ]
